### ISSUE TITLE
Update the license file

### ISSUE THREAD

**Issue by congysu** [OData/ValidationTool#4]
Rename the file to License.txt, and change name to OData-ValidationTool

**Comment by dingeins** [comment]
Great catch. I agree. Precise makes perfect. :)

The current unprecise version is however learnt from other Microsoft projects: https://github.com/Microsoft/dotnet/blob/master/LICENSE. 

I'll update the file according to the feedback.

**Comment by dingeins** [comment]
Just found that the OSS approval requires the file name to be "license.txt" and project name to be "OData-Validation Tool". Will adapt the proposal to it accordingly.

**Comment by dingeins** [comment]
@congysu Please review this PR: https://github.com/OData/ValidationTool/pull/5. After merging you may delete the branch.

**Comment by congysu** [comment]
License file updated: https://github.com/OData/ValidationTool/blob/master/License.txt
